# ============================================================
# ? NOM DE L'APPLICATION
# ============================================================
spring.application.name=api_fizanakara
server.port=3000

# ============================================================
# ? BASE DE DONN?ES POSTGRESQL
# ============================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/db_fizanakara_cotisation
spring.datasource.username=postgres
spring.datasource.password=mekill404
spring.datasource.driver-class-name=org.postgresql.Driver
spring.session.jdbc.initialize-schema=always

# ============================================================
# ? JPA / HIBERNATE
# ============================================================
# Cree / met a jour automatiquement les tables
spring.jpa.hibernate.ddl-auto=update
# Affiche les requetes SQL dans la console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Dialect PostgreSQL
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Active la gestion des dates @CreatedDate / @LastModifiedDate
spring.data.jpa.repositories.bootstrap-mode=default

#SUpprimer le query paresseux
spring.jpa.open-in-view=false

# ============================================================
# ? SPRING SECURITY (utilisateur de test)
# ============================================================
spring.security.user.name=admin
spring.security.user.password=1234

# ============================================================
# ? JWT CONFIGURATION
# ============================================================
jwt.secret=MyVeryLongSecretKeyForHS512AtLeast64BytesLongEnoughForSecureSigning1234567890abcdef
jwt.expiration=8640000
jwt.refresh-expiration=604800000

# ============================================================
# ? MAIL (pour Forgot Password)
# ============================================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=developer.nassai@gmail.com
spring.mail.password=dwuzwidnhxuzthwq 
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ============================================================
# ? CONFIGURATION R?INITIALISATION MOT DE PASSE
# ============================================================
# Dur?e d'expiration du token (en minutes, par d?faut 30)
app.token.expiration.minutes=30

# URL de base pour le lien de r�initialisation (adaptez ? votre frontend)
app.client.reset.url=https://localhost/admin/reset-password

# Sujet de l'e-mail de r?initialisation
app.email.reset.subject=Reinitialisation de mot de passe - Fizanakara

# Template du corps de l'e-mail (utilise %d pour les minutes, %s pour le lien)
app.email.reset.body=Bonjour,\n\nClique sur le lien suivant pour reinitialiser ton mot de passe (valide %d minutes) :\n\n%s\n\nSi tu n'as pas demand? ce mail, ignore-le.\n\nCordialement,\nL'equipe Fizanakara.